import { Paises } from '../interface/paises';

export const paises: Paises[] = [
    { nombreAPI: 'Afganistán',                      nombreSP: 'Afghanistan' },
    { nombreAPI: 'Albania',                         nombreSP: 'Albania' },
    { nombreAPI: 'Andorra',                         nombreSP: 'Andorra' },
    { nombreAPI: 'Angola',                          nombreSP: 'Angola' },
    { nombreAPI: 'Antigua and Barbuda',             nombreSP: 'Antigua y Barbuda' },
    { nombreAPI: 'Argentina',                       nombreSP: 'Argentina' },
    { nombreAPI: 'Armenia',                         nombreSP: 'Armenia' },
    { nombreAPI: 'Australia',                       nombreSP: 'Australia' },
    { nombreAPI: 'Austria',                         nombreSP: 'Austria' },
    { nombreAPI: 'Azerbaijan',                      nombreSP: 'Azerbaiyan' },
    { nombreAPI: 'Bahamas',                         nombreSP: 'Bahamas' },
    { nombreAPI: 'Bahrain',                         nombreSP: 'Bahrein' },
    { nombreAPI: 'Bangladesh',                      nombreSP: 'Bangladesh' },
    { nombreAPI: 'Barbados',                        nombreSP: 'Barbados' },
    { nombreAPI: 'Belarus',                         nombreSP: 'Bielorrusia' },
    { nombreAPI: 'Belgium',                         nombreSP: 'Belgica' },
    { nombreAPI: 'Benin',                           nombreSP: 'Benin' },
    { nombreAPI: 'Bhutan',                          nombreSP: 'Butan' },
    { nombreAPI: 'Bolivia',                         nombreSP: 'Bolivia' },
    { nombreAPI: 'Bosnia and Herzegovina',          nombreSP: 'Bosnia y Herzegovina' },
    { nombreAPI: 'Botswana',                        nombreSP: 'Botsuana' },
    { nombreAPI: 'Brazil',                          nombreSP: 'Brasil' },
    { nombreAPI: 'Bulgaria',                        nombreSP: 'Bulgaria' },
    { nombreAPI: 'Burkina Faso',                    nombreSP: 'Burkina Faso' },
    { nombreAPI: 'Cambodia',                        nombreSP: 'Camboya' },
    { nombreAPI: 'Cameroon',                        nombreSP: 'Camerun' },
    { nombreAPI: 'Canada',                          nombreSP: 'Canada' },
    { nombreAPI: 'Cape Verde',                      nombreSP: 'Cabo Verde' },
    { nombreAPI: 'Central African Republic',        nombreSP: 'Republica Centroafricana' },
    { nombreAPI: 'Chile',                           nombreSP: 'Chile' },
    { nombreAPI: 'China',                           nombreSP: 'China' },
    { nombreAPI: 'Colombia',                        nombreSP: 'Colombia' },
    { nombreAPI: 'Costa Rica',                      nombreSP: 'Costa Rica' },
    { nombreAPI: 'Croatia',                         nombreSP: 'Croacia' },
    { nombreAPI: 'Burundi',                         nombreSP: 'Burundi' },
    { nombreAPI: 'Cuba',                            nombreSP: 'Cuba' },
    { nombreAPI: 'Cyprus',                          nombreSP: 'Chipre' },
    { nombreAPI: 'Czech Republic',                  nombreSP: 'Republica checa' },
    { nombreAPI: 'Denmark',                         nombreSP: 'Dinamarca' },
    { nombreAPI: 'Dominica',                        nombreSP: 'Dominica' },
    { nombreAPI: 'Dominican Republic',              nombreSP: 'Republica Dominicana' },
    { nombreAPI: 'Ecuador',                         nombreSP: 'Ecuador' },
    { nombreAPI: 'Egypt',                           nombreSP: 'Egipto' },
    { nombreAPI: 'El Salvador',                     nombreSP: 'El Salvador' },
    { nombreAPI: 'Eritrea',                         nombreSP: 'Eritrea' },
    { nombreAPI: 'Estonia',                         nombreSP: 'Estonia' },
    { nombreAPI: 'Ethiopia',                        nombreSP: 'Etiopia' },
    { nombreAPI: 'Fiji',                            nombreSP: 'Fiyi' },
    { nombreAPI: 'Finland',                         nombreSP: 'Finlandia' },
    { nombreAPI: 'France',                          nombreSP: 'Francia' },
    { nombreAPI: 'Gabon',                           nombreSP: 'Gabon' },
    { nombreAPI: 'Gambia',                          nombreSP: 'Gambia' },
    { nombreAPI: 'Georgia',                         nombreSP: 'Georgia' },
    { nombreAPI: 'Germany',                         nombreSP: 'Alemania' },
    { nombreAPI: 'Ghana',                           nombreSP: 'Ghana' },
    { nombreAPI: 'Greece',                          nombreSP: 'Grecia' },
    { nombreAPI: 'Guatemala',                       nombreSP: 'Guatemala' },
    { nombreAPI: 'Guinea',                          nombreSP: 'Guinea' },
    { nombreAPI: 'Haiti',                           nombreSP: 'Haiti' },
    { nombreAPI: 'Holy See (Vatican City State)',   nombreSP: 'Ciudad del Vaticano' },
    { nombreAPI: 'Honduras',                        nombreSP: 'Honduras' },
    { nombreAPI: 'Hungary',                         nombreSP: 'Hungría' },
    { nombreAPI: 'Iceland',                         nombreSP: 'Islandia' },
    { nombreAPI: 'India',                           nombreSP: 'India' },
    { nombreAPI: 'Indonesia',                       nombreSP: 'Indonesia' },
    { nombreAPI: 'Iran, Islamic Republic of',       nombreSP: 'Iran' },
    { nombreAPI: 'Iraq',                            nombreSP: 'Irak' },
    { nombreAPI: 'Ireland',                         nombreSP: 'Irlanda' },
    { nombreAPI: 'Israel',                          nombreSP: 'Israel' },
    { nombreAPI: 'Italy',                           nombreSP: 'Italia' },
    { nombreAPI: 'Jamaica',                         nombreSP: 'Jamaica' },
    { nombreAPI: 'Japan',                           nombreSP: 'Japon' },
    { nombreAPI: 'Kazakhstan',                      nombreSP: 'Kazajistan' },
    { nombreAPI: 'Korea (South)',                   nombreSP: 'Corea del sur' },
    { nombreAPI: 'Kuwait',                          nombreSP: 'Kuwait' },
    { nombreAPI: 'Liberia',                         nombreSP: 'Liberia' },
    { nombreAPI: 'Lithuania',                       nombreSP: 'Lituania' },
    { nombreAPI: 'Luxembourg',                      nombreSP: 'Luxemburgo' },
    { nombreAPI: 'Macedonia, Republic of',          nombreSP: 'Macedonia' },
    { nombreAPI: 'Madagascar',                      nombreSP: 'Madagascar' },
    { nombreAPI: 'Malaysia',                        nombreSP: 'Malasia' },
    { nombreAPI: 'Maldives',                        nombreSP: 'Maldivas' },
    { nombreAPI: 'Mali',                            nombreSP: 'Mali' },
    { nombreAPI: 'Mauritania',                      nombreSP: 'Mauritania' },
    { nombreAPI: 'Mauritius',                       nombreSP: 'Mauricio' },
    { nombreAPI: 'Mexico',                          nombreSP: 'Mexico' },
    { nombreAPI: 'Moldova',                         nombreSP: 'Moldavia' },
    { nombreAPI: 'Monaco',                          nombreSP: 'Monaco' },
    { nombreAPI: 'Mongolia',                        nombreSP: 'Mongolia' },
    { nombreAPI: 'Montenegro',                      nombreSP: 'Montenegro' },
    { nombreAPI: 'Morocco',                         nombreSP: 'Marruecos' },
    { nombreAPI: 'Mozambique',                      nombreSP: 'Mozambique' },
    { nombreAPI: 'Myanmar',                         nombreSP: 'Birmania' },
    { nombreAPI: 'Nepal',                           nombreSP: 'Nepal' },
    { nombreAPI: 'Netherlands',                     nombreSP: 'Holanda' },
    { nombreAPI: 'New Zealand',                     nombreSP: 'Nueva Zelanda'},
    { nombreAPI: 'Nicaragua',                       nombreSP: 'Nicaragua' },
    { nombreAPI: 'Nigeria',                         nombreSP: 'Nigeria' },
    { nombreAPI: 'Norway',                          nombreSP: 'Noruega' },
    { nombreAPI: 'Oman',                            nombreSP: 'Oman' },
    { nombreAPI: 'Pakistan',                        nombreSP: 'Pakistan' },
    { nombreAPI: 'Palestinian Territory',           nombreSP: 'Palestina' },
    { nombreAPI: 'Panama',                          nombreSP: 'Panamá' },
    { nombreAPI: 'Paraguay',                        nombreSP: 'Paraguay' },
    { nombreAPI: 'Peru',                            nombreSP: 'Peru' },
    { nombreAPI: 'Philippines',                     nombreSP: 'Filipinas' },
    { nombreAPI: 'Poland',                          nombreSP: 'Polonia' },
    { nombreAPI: 'Portugal',                        nombreSP: 'Portugal' },
    { nombreAPI: 'Qatar',                           nombreSP: 'Catar' },
    { nombreAPI: 'Romania',                         nombreSP: 'Rumania' },
    { nombreAPI: 'Russian Federation',              nombreSP: 'Rusia' },
    { nombreAPI: 'San Marino',                      nombreSP: 'San Marino' },
    { nombreAPI: 'Saudi Arabia',                    nombreSP: 'Arabia Saudita' },
    { nombreAPI: 'Senegal',                         nombreSP: 'Senegal' },
    { nombreAPI: 'Serbia',                          nombreSP: 'Serbia' },
    { nombreAPI: 'Sierra Leone',                    nombreSP: 'Sierra Leona' },
    { nombreAPI: 'Singapore',                       nombreSP: 'Singapur' },
    { nombreAPI: 'Slovakia',                        nombreSP: 'Eslovaquia' },
    { nombreAPI: 'Slovenia',                        nombreSP: 'Eslovenia' },
    { nombreAPI: 'Somalia',                         nombreSP: 'Somalia' },
    { nombreAPI: 'South Africa',                    nombreSP: 'Sudafrica' },
    { nombreAPI: 'South Sudan',                     nombreSP: 'Sudan del Sur' },
    { nombreAPI: 'Spain',                           nombreSP: 'España' },
    { nombreAPI: 'Sri Lanka',                       nombreSP: 'Sri Lanka' },
    { nombreAPI: 'Sudan',                           nombreSP: 'Sudan' },
    { nombreAPI: 'Suriname',                        nombreSP: 'Surinam' },
    { nombreAPI: 'Swaziland',                       nombreSP: 'Swazilandia' },
    { nombreAPI: 'Sweden',                          nombreSP: 'Suecia' },
    { nombreAPI: 'Switzerland',                     nombreSP: 'Suiza' },
    { nombreAPI: 'Syrian Arab Republic (Syria)',    nombreSP: 'Siria' },
    { nombreAPI: 'Taiwan, Republic of China',       nombreSP: 'Taiwan' },
    { nombreAPI: 'Tanzania, United Republic of',    nombreSP: 'Tanzania' },
    { nombreAPI: 'Thailand',                        nombreSP: 'Tailandia' },
    { nombreAPI: 'Togo',                            nombreSP: 'Togo' },
    { nombreAPI: 'Trinidad and Tobago',             nombreSP: 'Trinidad y Tobago' },
    { nombreAPI: 'Uganda',                          nombreSP: 'Uganda' },
    { nombreAPI: 'Ukraine',                         nombreSP: 'Ucrania' },
    { nombreAPI: 'United Arab Emirates',            nombreSP: 'Emiratos Arabes Unidos' },
    { nombreAPI: 'United Kingdom',                  nombreSP: 'Reino Unido' },
    { nombreAPI: 'United States of America',        nombreSP: 'Estados Unidos' },
    { nombreAPI: 'Uruguay',                         nombreSP: 'Uruguay' },
    { nombreAPI: 'Uzbekistan',                      nombreSP: 'Uzbekistan' },
    { nombreAPI: 'Venezuela (Bolivarian Republic)', nombreSP: 'Venezuela' },
    { nombreAPI: 'Viet Nam',                        nombreSP: 'Vietnam' },
    { nombreAPI: 'Yemen',                           nombreSP: 'Yemen' },
    { nombreAPI: 'Zambia',                          nombreSP: 'Zambia' },
    { nombreAPI: 'Zimbabwe',                        nombreSP: 'Zimbabue' }
];
